<?php

/**
 * Include acf fields instead of import
 * 
 */
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_550becd621878',
	'title' => 'Puff - Senaste posterna i nätverket',
	'fields' => array (
		array (
			'key' => 'field_550c235a9ff6c',
			'label' => 'Titel',
			'name' => 'latest_subsite_posts_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_559b6a8985d67',
			'label' => 'Titellänk',
			'name' => 'latest_subsite_posts_title_link',
			'prefix' => '',
			'type' => 'url',
			'instructions' => 'Ange en länk dit pufftiteln skall länkas',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_559b5f5937373',
			'label' => 'Bild',
			'name' => 'latest_subsite_posts_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Rekommenderad bildstorlek: 640px x 320px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_550c0eb7f431a',
			'label' => 'Kategorier',
			'name' => 'latest_subsite_posts_categories',
			'prefix' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'sitewidecats',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'load_save_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_550c237e9ff6d',
			'label' => 'Max antal inlägg',
			'name' => 'latest_subsite_posts_max_count',
			'prefix' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:senaste-inlaggen-subsajter',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;
?>