<?php

/**
 * Include acf fields instead of import
 * 
 */
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_545cb529d928a',
	'title' => 'Innehållsblock',
	'fields' => array (
		array (
			'key' => 'field_545cb53512c60',
			'label' => 'Innehållsblock',
			'name' => 'content_block',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => 'Välj dina innehållsblock.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Lägg till innehållsblock',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '546dde5ca1c49',
					'name' => 'slider_block',
					'label' => 'Bildspel',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_546de6cf2e105',
							'label' => 'Titel',
							'name' => 'slider_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_546de912bc7a1',
							'label' => 'Bilder/Video',
							'name' => 'slider_content',
							'prefix' => '',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'button_label' => 'Lägg till bild/video',
							'min' => '',
							'max' => '',
							'layouts' => array (
								array (
									'key' => '546de917517b3',
									'name' => 'slider_image',
									'label' => 'Bild',
									'display' => 'row',
									'sub_fields' => array (
										array (
											'key' => 'field_546dde76a1c4b',
											'label' => 'Bild',
											'name' => 'slider_image_content',
											'prefix' => '',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'preview_size' => 'medium',
											'library' => 'all',
											'min_width' => 0,
											'min_height' => 0,
											'min_size' => 0,
											'max_width' => 0,
											'max_height' => 0,
											'max_size' => 0,
											'mime_types' => '',
										),
										array (
											'key' => 'field_546dea1e63e40',
											'label' => 'Text',
											'name' => 'slider_image_text',
											'prefix' => '',
											'type' => 'text',
											'instructions' => 'Text som skrivs ut på bilden.',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
										array (
											'key' => 'field_546ddf55a1c50',
											'label' => 'Länk',
											'name' => 'slider_image_url',
											'prefix' => '',
											'type' => 'url',
											'instructions' => 'Länka bilden.',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '546de98f996f2',
									'name' => 'slider_video',
									'label' => 'Video',
									'display' => 'row',
									'sub_fields' => array (
										array (
											'key' => 'field_546ddeaea1c4d',
											'label' => 'Videolänk',
											'name' => 'slider_video_url',
											'prefix' => '',
											'type' => 'url',
											'instructions' => 'URL till YouTube/Vimeo.',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
										),
										array (
											'key' => 'field_546ddecda1c4e',
											'label' => 'Text',
											'name' => 'slider_video_text',
											'prefix' => '',
											'type' => 'text',
											'instructions' => 'Text på videon.',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
										array (
											'key' => 'field_546ee58a84012',
											'label' => 'Bild',
											'name' => 'slider_video_image',
											'prefix' => '',
											'type' => 'image',
											'instructions' => 'Om du vill använda en egen bild som poster för videon.',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'preview_size' => 'medium',
											'library' => 'all',
											'min_width' => 0,
											'min_height' => 0,
											'min_size' => 0,
											'max_width' => 0,
											'max_height' => 0,
											'max_size' => 0,
											'mime_types' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '545cb555d64fd',
					'name' => 'text_block',
					'label' => 'Text',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5464802e0e910',
							'label' => 'Titel',
							'name' => 'text_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Ifall ni vill ha en titel till innehållsblocket, fyll i den här.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_546b0dd62fa89',
							'label' => 'Kolumner',
							'name' => 'text_columns',
							'prefix' => '',
							'type' => 'select',
							'instructions' => 'Välj antalet textkolumner ni vill ha.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								1 => 1,
								2 => 2,
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_545cb55e12c61',
							'label' => 'Innehåll',
							'name' => 'text_content',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => 'Innehållet för blocket.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_546b0e272fa8a',
							'label' => 'Innehåll',
							'name' => 'text_content_2',
							'prefix' => '',
							'type' => 'wysiwyg',
							'instructions' => 'Innehållet för blocket.',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_546b0dd62fa89',
										'operator' => '==',
										'value' => '2',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '545cb6bcdcf21',
					'name' => 'gallery_block',
					'label' => 'Galleri',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_5464807961b44',
							'label' => 'Titel',
							'name' => 'gallery_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => 'Ifall ni vill ha en titel till innehållsblocket, fyll i den här.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_545cb6c2dcf22',
							'label' => 'Galleri',
							'name' => 'gallery_content',
							'prefix' => '',
							'type' => 'gallery',
							'instructions' => 'Välj era bilder ni vill presentera i galleriet.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '546c4df5aef9f',
					'name' => 'boxes_block',
					'label' => 'Puffar',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_546c4e1baefa0',
							'label' => 'Titel',
							'name' => 'boxes_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_546c4e6aaefa2',
							'label' => 'Puff',
							'name' => 'boxes_content',
							'prefix' => '',
							'type' => 'relationship',
							'instructions' => 'Välj puffar att visa på sidan. Dessa hämtas från biblioteket innehållande puffar. Vill du uppdatera innehåll i puffarna gå till "Puffar" i vänstermenyn.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'boxes',
							),
							'taxonomy' => '',
							'filters' => array (
								0 => 'search',
								1 => 'taxonomy',
							),
							'elements' => '',
							'max' => '',
							'return_format' => 'id',
						),
						array (
							'key' => 'field_54f96af002c8e',
							'label' => 'Antal puffar',
							'name' => 'boxes_width',
							'prefix' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								2 => 2,
								3 => 3,
								4 => 4,
							),
							'default_value' => array (
								3 => 3,
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '547f076ccceeb',
					'name' => 'latest_posts_block',
					'label' => 'Senaste inläggen',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_547f0793cceec',
							'label' => 'Titel',
							'name' => 'latest_posts_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_547f07dccceed',
							'label' => 'Kategori',
							'name' => 'latest_posts_category',
							'prefix' => '',
							'type' => 'taxonomy',
							'instructions' => 'Senaste inläggen från valda kategorier kommer att visas. Väljer du ingen kategori visas samtliga inlägg.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'load_save_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array (
							'key' => 'field_547f0829cceee',
							'label' => 'Antal inlägg',
							'name' => 'latest_posts_limit',
							'prefix' => '',
							'type' => 'number',
							'instructions' => 'Max antal inlägg som ska visas.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 4,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54f0345ae6cc1',
					'name' => 'faq_block',
					'label' => 'FAQ',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54f0345ae6cc2',
							'label' => 'Titel',
							'name' => 'faq_block_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_54f0345ae6cc3',
							'label' => 'Kategori',
							'name' => 'faq_block_category',
							'prefix' => '',
							'type' => 'taxonomy',
							'instructions' => 'Senaste inläggen från valda kategorier kommer att visas. Väljer du ingen kategori visas samtliga inlägg.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'load_save_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54eef16518508',
					'name' => 'campaign_block',
					'label' => 'Kampanj',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54eef16518509',
							'label' => 'Titel',
							'name' => 'campaign_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_54eef1651850a',
							'label' => 'Kategori',
							'name' => 'campaign_category',
							'prefix' => '',
							'type' => 'taxonomy',
							'instructions' => 'Senaste inläggen från valda kategorier kommer att visas. Väljer du ingen kategori visas samtliga inlägg.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'load_save_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array (
							'key' => 'field_54ef373d56adc',
							'label' => 'Kampanjyta',
							'name' => 'campaign_content',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array (
								array (
									'key' => 'field_55d43c809c1ba',
									'label' => 'Kampanjbild',
									'name' => 'campaign_image',
									'prefix' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_55d43c809c1bb',
									'label' => 'Text',
									'name' => 'campaign_image_text',
									'prefix' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_55d43c809c1bc',
									'label' => 'Låsa bilden',
									'name' => 'campaign_image_lock',
									'prefix' => '',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'Ja' => 'Ja',
									),
									'default_value' => array (
										'' => '',
									),
									'layout' => 'vertical',
								),
								array (
									'key' => 'field_55d43c809c1bd',
									'label' => 'Länk',
									'name' => 'campaign_image_url',
									'prefix' => '',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => '',
									'taxonomy' => '',
									'allow_null' => 0,
									'multiple' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55d43c7f9c1b6',
					'name' => 'slider_special_block',
					'label' => 'Bildspel med kalenderpuff',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_55d43c7f9c1b7',
							'label' => 'Titel',
							'name' => 'campaign_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55d43c809c1b9',
							'label' => 'Kampanjyta',
							'name' => 'slider_special_content',
							'prefix' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array (
								array (
									'key' => 'field_55d43df1d97ac',
									'label' => 'Bild',
									'name' => 'slider_image',
									'prefix' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_55d4418778c16',
									'label' => 'Text',
									'name' => 'slider_image_text',
									'prefix' => '',
									'type' => 'text',
									'instructions' => 'Text som skrivs ut på bilden.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_55d485c5bb957',
									'label' => 'Länk',
									'name' => 'slider_image_url',
									'prefix' => '',
									'type' => 'url',
									'instructions' => 'Länka bilden.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54802fc04f035',
					'name' => 'form_block',
					'label' => 'Formulär',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54802fca4f036',
							'label' => 'Titel',
							'name' => 'form_title',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_54802fd84f037',
							'label' => 'Formulär',
							'name' => 'form_id',
							'prefix' => '',
							'type' => 'gravity_forms_field',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'allow_null' => 0,
							'allow_multiple' => 0,
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-advanced.php',
			),
		),
	),
	'menu_order' => -1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'featured_image',
	),
));

register_field_group(array (
	'key' => 'group_552d101245fcc',
	'title' => 'Blogginställningar',
	'fields' => array (
		array (
			'key' => 'field_552d101de6608',
			'label' => 'Bild',
			'name' => 'sk-blog-image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Optimal bildstorlek 285px x 285px.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5535fd2fa111a',
			'label' => 'Beskrivning',
			'name' => 'sk-blog-desc',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-blogginstallningar',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_54ed99eddf5a4',
	'title' => 'FAQ',
	'fields' => array (
		array (
			'key' => 'field_54ed99ece15f6',
			'label' => 'Svar',
			'name' => 'svar',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Ange frågans svar här',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'very_simple',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_54ed9a25e15f7',
			'label' => 'Referenser',
			'name' => 'referenser',
			'prefix' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'max' => '',
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'faq',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_5476e1c779c8b',
	'title' => 'Högerspalt',
	'fields' => array (
		array (
			'key' => 'field_5476e2008da59',
			'label' => 'Puffar',
			'name' => 'sidebar_boxes',
			'prefix' => '',
			'type' => 'relationship',
			'instructions' => 'Välj puffar att visa på sidan. Dessa hämtas från biblioteket innehållande puffar. Vill du uppdatera innehåll i puffarna gå till "Puffar" i vänstermenyn.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'boxes',
			),
			'taxonomy' => '',
			'filters' => array (
				0 => 'search',
				1 => 'taxonomy',
			),
			'elements' => '',
			'max' => '',
			'return_format' => 'id',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-advanced.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_550c17872c11a',
	'title' => 'Paneler',
	'fields' => array (
		array (
			'key' => 'field_550c18f91b367',
			'label' => 'Paneler',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_550c194c701e4',
			'label' => '',
			'name' => '',
			'prefix' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Sed posuere consectetur est at lobortis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_550c1935be9ec',
			'label' => 'Hantera paneler',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_550c1863a2921',
			'label' => 'Paneler',
			'name' => 'sk_panels',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Lägg till rad',
			'sub_fields' => array (
				array (
					'key' => 'field_550c1891a2922',
					'label' => 'Rubrik',
					'name' => 'sk_panel_header',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_550c18a7a2923',
					'label' => 'Innehåll',
					'name' => 'sk_panel_content',
					'prefix' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_546c661cce792',
	'title' => 'Puff - Bild',
	'fields' => array (
		array (
			'key' => 'field_546c9ab844c0f',
			'label' => 'Bild',
			'name' => 'box_image_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Bilden ska vara mins 540x405.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_546c662f06f82',
			'label' => 'Text',
			'name' => 'box_image_content',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_546c67b806f84',
			'label' => 'Extern länk',
			'name' => 'box_image_is_external',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Ja' => 'Ja',
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_546c684906f86',
			'label' => 'Länk',
			'name' => 'box_image_internal_link',
			'prefix' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_546c67b806f84',
						'operator' => '!=',
						'value' => 'Ja',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
				1 => 'post',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_546c67fb06f85',
			'label' => 'Länk',
			'name' => 'box_image_external_link',
			'prefix' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_546c67b806f84',
						'operator' => '==',
						'value' => 'Ja',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_546c6dacabbbc',
			'label' => 'Nytt fönster',
			'name' => 'box_image_new_window',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => 'Vill du att besökarna ska öppna länken i samma fönster eller i ett nytt?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Ja' => 'Ja',
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:bild',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_54f42540c9cfe',
	'title' => 'Puff - Bild och länklista',
	'fields' => array (
		array (
			'key' => 'field_54f433cb1f5dc',
			'label' => 'Titel',
			'name' => 'image_and_textlist_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54f425434f89b',
			'label' => 'Bild',
			'name' => 'image_and_textlist_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_54f425924f89c',
			'label' => 'Länklista',
			'name' => 'image_and_textlist_links',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Lägg till länk',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '54f425af054d2',
					'name' => 'image_and_textlist_internal_link',
					'label' => 'Intern länk',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54f435245d205',
							'label' => 'Länktext',
							'name' => 'text',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_54f425e24f89e',
							'label' => 'Länk',
							'name' => 'link',
							'prefix' => '',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => '',
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54f5ad9efc9f4',
					'name' => 'image_and_textlist_external_link',
					'label' => 'Extern länk',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54f5add5fc9f5',
							'label' => 'Länktext',
							'name' => 'text',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_54f5adf3fc9f6',
							'label' => 'Länk',
							'name' => 'link',
							'prefix' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_54f5ae47fc9f7',
							'label' => 'Öppnas i nytt fönster',
							'name' => 'new_window',
							'prefix' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Ja' => 'Ja',
							),
							'default_value' => array (
							),
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:bild-och-lanklista',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_5476ecd955800',
	'title' => 'Puff - Dokument',
	'fields' => array (
		array (
			'key' => 'field_5477346726a03',
			'label' => 'Titel',
			'name' => 'box_documents_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5476ece4656b8',
			'label' => 'Filer',
			'name' => 'box_documents',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Lägg till fil',
			'sub_fields' => array (
				array (
					'key' => 'field_5476ed31656b9',
					'label' => 'Fil',
					'name' => 'box_documents_file',
					'prefix' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'library' => 'all',
					'min_size' => 0,
					'max_size' => 0,
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:dokument',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_546f53715c146',
	'title' => 'Puff - Facebook',
	'fields' => array (
		array (
			'key' => 'field_546f53928d4ba',
			'label' => 'Länk till facebook-sida',
			'name' => 'box_facebook_url',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:facebook-flode',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_552a66e67d038',
	'title' => 'Puff - Kalender',
	'fields' => array (
		array (
			'key' => 'field_552a66ed61af5',
			'label' => 'calendar_categories',
			'name' => 'calendar_categories',
			'prefix' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'tribe_events_cat',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'load_save_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:kalender',
			),
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_54802c400c6cc',
	'title' => 'Puff - Kontaktkort',
	'fields' => array (
		array (
			'key' => 'field_54802cf5acea1',
			'label' => 'Bild',
			'name' => 'box_contact_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_54802d8eacea2',
			'label' => 'Namn',
			'name' => 'box_contact_name',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54806e1a47ff6',
			'label' => 'Roll',
			'name' => 'box_contact_role',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54802dbdacea3',
			'label' => 'E-post',
			'name' => 'box_contact_email',
			'prefix' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_54802e49acea4',
			'label' => 'Telefon',
			'name' => 'box_contact_phone',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54802e71acea5',
			'label' => 'Mobil',
			'name' => 'box_contact_mobile',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:kontaktkort',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_546c6c3e516df',
	'title' => 'Puff - Länklista',
	'fields' => array (
		array (
			'key' => 'field_547f2ebd343f9',
			'label' => 'Titel',
			'name' => 'box_links_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_546eeb66612ac',
			'label' => 'Länk',
			'name' => 'box_links',
			'prefix' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Lägg till länk',
			'min' => 1,
			'max' => '',
			'layouts' => array (
				array (
					'key' => '546eeb6dd5595',
					'name' => 'external_link',
					'label' => 'Extern länk',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_546eebc1612ad',
							'label' => 'Länktext',
							'name' => 'text',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_546eebcc612ae',
							'label' => 'Länk',
							'name' => 'link',
							'prefix' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://sundsvall.se',
						),
						array (
							'key' => 'field_546eebd7612af',
							'label' => 'Öppna i nytt fönster',
							'name' => 'new_window',
							'prefix' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Ja' => 'Ja',
							),
							'default_value' => array (
							),
							'layout' => 'vertical',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '546eebef612b0',
					'name' => 'internal_link',
					'label' => 'Intern länk',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_546eec281eeb5',
							'label' => 'Länktext',
							'name' => 'text',
							'prefix' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_546eebf9612b1',
							'label' => 'Länk',
							'name' => 'link',
							'prefix' => '',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'post',
								1 => 'page',
							),
							'taxonomy' => '',
							'allow_null' => 0,
							'multiple' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:lanklista',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_547496dedd0f6',
	'title' => 'Puff - Senaste inläggen',
	'fields' => array (
		array (
			'key' => 'field_5474988b460cb',
			'label' => 'Titel',
			'name' => 'box_latest_posts_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Senaste nyheterna',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54749781460c9',
			'label' => 'Kategori',
			'name' => 'box_latest_posts_category',
			'prefix' => '',
			'type' => 'taxonomy',
			'instructions' => 'Senaste inläggen från valda kategorier kommer att visas. Väljer du ingen kategori visas samtliga inlägg.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'load_save_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_54749801460ca',
			'label' => 'Antal inlägg',
			'name' => 'box_latest_posts_limit',
			'prefix' => '',
			'type' => 'number',
			'instructions' => 'Max antal inlägg som ska visas.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 5,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 20,
			'step' => 0,
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:senaste-inlaggen',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_550becd621878',
	'title' => 'Puff - Senaste posterna i nätverket',
	'fields' => array (
		array (
			'key' => 'field_550c235a9ff6c',
			'label' => 'Titel',
			'name' => 'latest_subsite_posts_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_559b6a8985d67',
			'label' => 'Titellänk',
			'name' => 'latest_subsite_posts_title_link',
			'prefix' => '',
			'type' => 'url',
			'instructions' => 'Ange en länk dit pufftiteln skall länkas',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_559b5f5937373',
			'label' => 'Bild',
			'name' => 'latest_subsite_posts_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Rekommenderad bildstorlek: 640px x 320px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_550c0eb7f431a',
			'label' => 'Kategorier',
			'name' => 'latest_subsite_posts_categories',
			'prefix' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'sitewidecats',
			'field_type' => 'checkbox',
			'allow_null' => 0,
			'load_save_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_550c237e9ff6d',
			'label' => 'Max antal inlägg',
			'name' => 'latest_subsite_posts_max_count',
			'prefix' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:senaste-inlaggen-subsajter',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_54eb2af779465',
	'title' => 'Puff - Text',
	'fields' => array (
		array (
			'key' => 'field_54eb2afe4119f',
			'label' => 'Text',
			'name' => 'box_text_content',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'very_simple',
			'media_upload' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'boxes',
			),
			array (
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'box-type:text',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_545b82410e0f2',
	'title' => 'Sidfot',
	'fields' => array (
		array (
			'key' => 'field_54e6f608a1ddb',
			'label' => 'Kolumner i sidfoten',
			'name' => 'footer_columns',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => 4,
			'layout' => 'block',
			'button_label' => 'Lägg till ny kolumn',
			'sub_fields' => array (
				array (
					'key' => 'field_54e6f637a1ddc',
					'label' => 'Kolumner',
					'name' => 'footer_column',
					'prefix' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'media_upload' => 1,
					'toolbar' => 'full',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-sidfot',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_545b731c895bb',
	'title' => 'Sidhuvud',
	'fields' => array (
		array (
			'key' => 'field_545b732dff2fa',
			'label' => 'Logotyp',
			'name' => 'site_logo',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Välj en logotyp att visa i webbplatsens sidhuvud. Ifall ingen logotyp finns kommer webbplatsens titel skrivas ut istället. Logotypen bör vara max 200px bred och max 150px hög. Ska laddas upp i .jpg eller .png.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_545b75d307f6b',
			'label' => 'Bakgrundsbild',
			'name' => 'site_header_bg',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'Välj en bakgrundsbild som visas i webbplatsens sidhuvud. Bakgrundsbilden bör vara 1500x400px.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-sidhuvud',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_547dd339c6fcf',
	'title' => 'Sidnställningar',
	'fields' => array (
		array (
			'key' => 'field_547dd3400592d',
			'label' => 'Visa sidomeny',
			'name' => 'hide_sidebar_menu',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Visa meny',
			'default_value' => 1,
		),
		array (
			'key' => 'field_548968a60a802',
			'label' => 'Visa huvudrubrik (H1)',
			'name' => 'show_h1',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Visa rubrik',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-advanced.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_545cb7c62b66d',
	'title' => 'Tema',
	'fields' => array (
		array (
			'key' => 'field_545b8b365752b',
			'label' => 'Temafärg',
			'name' => 'site_color',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Välj temafärg för din webbplats. Färgerna är från Sundvalls kommunkoncerns grafiska profil.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'rodon' => 'Rödön <span style="background: #9f291d; vertical-align: middle; display: inline-block; width: 1.4em; height: 1.4em; border-radius: 3px; margin: 0 .3em;"></span>',
				'solum' => 'Solum <span style="background: #d64c13; vertical-align: middle; display: inline-block; width: 1.4em; height: 1.4em; border-radius: 3px; margin: 0 .3em;"></span>',
				'gronsta' => 'Grönsta <span style="background: #006b37; vertical-align: middle; display: inline-block; width: 1.4em; height: 1.4em; border-radius: 3px; margin: 0 .3em;"></span>',
				'vattjom' => 'Vattjom <span style="background: #0064ad; vertical-align: middle; display: inline-block; width: 1.4em; height: 1.4em; border-radius: 3px; margin: 0 .3em;"></span>',
				'bjornstigen' => 'Björnstigen <span style="background: #5b1f78; vertical-align: middle; display: inline-block; width: 1.4em; height: 1.4em; border-radius: 3px; margin: 0 .3em;"></span>',
				'juniskar' => 'Juniskär <span style="background: #a90074; vertical-align: middle; display: inline-block; width: 1.4em; height: 1.4em; border-radius: 3px; margin: 0 .3em;"></span>',
				'svartvik' => 'Svartvik <span style="background: #5c6a70; vertical-align: middle; display: inline-block; width: 1.4em; height: 1.4em; border-radius: 3px; margin: 0 .3em;"></span>',
				'tranviken' => 'Tranviken <span style="background: #a69850; vertical-align: middle; display: inline-block; width: 1.4em; height: 1.4em; border-radius: 3px; margin: 0 .3em;"></span>',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-tema',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_551d247f66ad4',
	'title' => 'Vänsterspalt',
	'fields' => array (
		array (
			'key' => 'field_551d247f69fe6',
			'label' => 'Puffar',
			'name' => 'sidebar_boxes_left',
			'prefix' => '',
			'type' => 'relationship',
			'instructions' => 'Välj puffar att visa på sidan. Dessa hämtas från biblioteket innehållande puffar. Vill du uppdatera innehåll i puffarna gå till "Puffar" i vänstermenyn.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'boxes',
			),
			'taxonomy' => '',
			'filters' => array (
				0 => 'search',
				1 => 'taxonomy',
			),
			'elements' => '',
			'max' => '',
			'return_format' => 'id',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-advanced.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;
?>